import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex`}
      >
        <nav className="w-64 bg-gray-100 p-4 border-r">
          <div className="font-semibold mb-4 text-lg">Menu</div>
          <ul className="space-y-2">
            {/* <li>
              <Link href="/" className="hover:text-blue-600">
                Home
              </Link>
            </li> */}
            <li>
              <Link href="/" className="hover:text-blue-600">
                Bill
              </Link>
            </li>
            {/* Add more menu items as needed */}
          </ul>
        </nav>
        <main className="flex-1 p-8">
          {children}
        </main>
      </body>
    </html>
  );
}
